In [6]:
#functioning of pandas(22UAI024)
import numpy as np
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


In [7]:
# Create a 2D array (matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)


2D Array:
[[1 2 3]
 [4 5 6]]


In [8]:
# Shape and size of array
print("Shape of 2D Array:", array_2d.shape)
print("Number of elements:", array_2d.size)

Shape of 2D Array: (2, 3)
Number of elements: 6


In [9]:
# Arithmatic operations
array_sum = array_1d + 10
print("Array after addition:")
print(array_sum)
array_product = array_1d * 2
print("Array after multiplication:")
print(array_product)


Array after addition:
[11 12 13 14 15]
Array after multiplication:
[ 2  4  6  8 10]


In [10]:
# Accessing a specific element
element = array_2d[0, 1]  
print("Element at [0, 1]:", element)

# Slicing an array
sliced_array = array_2d[0, :]
print("Sliced array (first row):")
print(sliced_array)

Element at [0, 1]: 2
Sliced array (first row):
[1 2 3]


In [11]:
# Compute mean
mean_value = np.mean(array_1d)
print("Mean value:", mean_value)

# Compute standard deviation
std_deviation = np.std(array_1d)
print("Standard deviation:", std_deviation)

Mean value: 3.0
Standard deviation: 1.4142135623730951


In [12]:
# Find minimum and maximum values
min_value = np.min(array_1d)
max_value = np.max(array_1d)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 1
Maximum value: 5


In [14]:
# Create an array of zeros
zeros_array = np.zeros((2, 3))
print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
